config/routes.rb
Rails.application.routes.draw do
  root to: "products#index"

  resources :coupons, only: [:edit, :index, :create, :update, :new, :destroy]
  resources :products, only: [:edit, :index, :create, :update, :new]
  resource :cart, only: [:show]
  resource :checkout, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
end

app/models/checkout.rb
class Checkout < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def total_price
    unit_price * quantity
  end

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items

  # default_scope { where(active: true) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    if Order.count > 0 && !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  before_action :set_coupon, only: [:edit, :update, :destroy]

  def index
    @coupons = Coupon.all
  end

  def new
  	@coupon = Coupon.new
  end

  def edit
  end

  def create
  	@coupon = Coupon.new(coupon_params)
  	if @coupon.save
  		redirect_to coupons_url, notice: 'Cupom criado com sucesso.'
  	else
  		render action: 'new'
  	end
  end

  def update
  	if @coupon.update(coupon_params)
  		redirect_to coupons_url, notice: 'Cupom atualizado com sucesso.'
  	else
  		render action: 'edit'
  	end
  end

  def destroy
    @coupon.destroy
    redirect_to coupons_url, notice: 'Coupon was successfully destroyed.'
  end

	private
	  # Use callbacks to share common setup or constraints between actions.
	  def set_coupon
	    @coupon = Coupon.find(params[:id])
	  end

	  # Only allow a trusted parameter "white list" through.
	  def coupon_params
	    params.require(:coupon).permit(:description, :minimum_value, :percent)
	  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    @order = current_order
    @order_item = @order.order_items.new(order_item_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end

private
  def order_item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update]

  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end

  def new
  	@product = Product.new
  	# @product.category_id = params['category_id']
  end

  def edit
  end

  def create
  	@product = Product.new(product_params)
  	if @product.save
  		redirect_to products_path, notice: 'Produto criado com sucesso.'
  	else
  		render action: 'new'
  	end
  end

  def update
  	if @product.update(product_params)
  		redirect_to products_path, notice: 'Produto atualizado com sucesso.'
  	else
  		render action: 'edit'
  	end
  end

	private
	  # Use callbacks to share common setup or constraints between actions.
	  def set_product
	    @product = Product.find(params[:id])
	  end

	  # Only allow a trusted parameter "white list" through.
	  def product_params
	    params.require(:product).permit(:name, :price, :active)
	  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper

  def minimum_value
    Coupon.minimum(:minimum_value).to_f
  end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right"> <%= t('unit_price') %> <span style="color: green"><%= number_to_currency order_item.unit_price, unit: "R$", separator: ",", delimiter: "" %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit t('update_quantity'), class: "btn btn-primary" %>
              <%= link_to t('delete'), order_item, { data: { confirm: "Tem certeza de que deseja apagar o produto '#{order_item.product.name}' do seu carrinho?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right"> <%= t('total_price') %> <span style="color: green"><%= number_to_currency order_item.total_price, unit: "R$", separator: ",", delimiter: ""%></span></h4>
      <% end %>
    </div>

  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="actions" align="right">
	<%= link_to t('back_prod'), products_path, class: "btn btn-default"%>
 	<% if current_order.subtotal >= t('value_min') %>
 		<%= link_to t('checkout'), checkout_path, class: "btn btn-success"%>
 	<% else %>
    	<%= link_to t('checkout'), checkout_path,
    	{ data: { confirm: "Sua pedido nåo atingiu valor minimo de '#{number_to_currency minimum_value, unit: "R$", separator: ",", delimiter: ""}'
    						nåo e possivel finalizar!" },
     	remote: true, class: "btn btn-warning" } %>
	<% end %>
</div>
<br>
<% if @order_items.size == 0 %>
  <p class="text-center">
    Não existem itens no seu carrinho de compras.  Por favor <%= link_to "Volte", root_path %> e adicionar alguns itens ao seu carrinho.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>

app/views/checkouts/_checkout_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right"> <%= t('unit_price') %> <span style="color: green"><%= number_to_currency order_item.unit_price, unit: "R$", separator: ",", delimiter: "" %></span></h4>
        <h4 class="text-right"> <%= t('quantity') %> <span style="color: green"><%= order_item.quantity.to_i %></span></h4>
        <h4 class="text-right"> <%= t('total_price') %> <span style="color: green"><%= number_to_currency order_item.total_price, unit: "R$", separator: ",", delimiter: ""%></span></h4>
      <% end %>
    </div>

  </div>
</div>

app/views/checkouts/_shopping_checkout.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    Não existem pedido de compras confirmado. Por favor <%= link_to "Volte", root_path %> confirma compra do seu carrinho.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'checkouts/checkout_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

app/views/checkouts/show.html.erb
<div class="" align="right">
	<%= link_to t('back_prod'), products_path, class: "btn btn-default"%>
	<h3> Pedido Confirmados </h3>
</div>
<div class="shopping-checkout">
  <%= render "shopping_checkout" %>
</div>

app/views/coupons/_form.html.erb
<%= form_for(@coupon, :multipart => true) do |f| %>
  <% if @coupon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coupon.errors.count, "error") %> prohibited this item from being saved:</h2>
      <ul>
      <% @coupon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :minimum_value %><br>
    <%= f.number_field :minimum_value, min: 1 %>
  </div>
  <div class="field">
    <%= f.label :percent %><br>
    <%= f.number_field :percent, min: 1 %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coupons/edit.html.erb
<h1>Modificar Cupom</h1>

<%= render 'form' %>

<%= link_to 'Show', @coupon %> |
<%= link_to 'Back', coupons_path %>

app/views/coupons/index.html.erb
<div align="right">
	<%= link_to t('new_coupon'), new_coupon_path, class: "btn btn-primary"%>
</div>
<h3 class="text-center"> <%= t('coupons') %> </h3>

<table>
  <thead>
    <tr>
      <th>Descriçåo</th>
      <th></th>
      <th>Valor Minimo</th>
      <th></th>
      <th>Percentual</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @coupons.each do |coupon| %>
      <tr>
        <td><%= coupon.description %></td>
        <th></th>
        <td><%= coupon.minimum_value %></td>
        <th></th>
        <td><%= coupon.percent %></td>
        <th></th>
        <td><%= link_to 'Edit', edit_coupon_path(coupon) %></td>
        <th></th>
        <td><%= link_to 'Destroy', coupon, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('new_coupon'), new_coupon_path %>

app/views/coupons/new.html.erb
<h1>Novo Cupom</h1>

<%= render 'form' %>

<%= link_to 'Back', coupons_path %>

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} #{t('result')} ( #{number_to_currency current_order.subtotal, unit: "R$", separator: ",", delimiter: ""} )", cart_path, class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShopApp</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <% if request.ssl? %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% else %>
    <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% end %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <h1><%= link_to t('store'), root_path %></h1>
      </div>
      <div class="col-xs-6 text-right">
        <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
      </div>
    </div>
    <hr>
    <%= yield %>
  </div>

</body>
</html>

app/views/order_items/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
alert("not valid.")
<% else %>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/order_items/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/order_items/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/products/_form.html.erb
<%= form_for(@product, :multipart => true) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price, min: 1 %>
  </div>
  <div class="field">
	<%= f.label :active %> <br>
	<%= select("product", "active",
				options_for_select([["Visivel", true], ["Invisivel", false]], @product.active),
				{include_blank: false}) %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-6">
      <h4><%= product.name %></small></h4>
    </div>

    <div class="col-xs-6">
      <%= form_for order_item, remote: true do |f| %>
      <h4 class="text-right"> <%= t('unit_price') %> <span style="color: green">
      	<%= number_to_currency product.price, unit: "R$", separator: ",", delimiter: "" %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit t('add_cart'), class: "btn btn-success" %>
            <%= link_to t('edit_cart'), edit_product_path(product.id), class: "btn btn-default" %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/products/edit.html.erb
<h1>Modificar Produto</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div align="right">
	<%= link_to t('new_prod'), new_product_path, class: "btn btn-primary"%>
</div>
<% if @products.size == 0 %>
   <p class="text-center">
    	Não existem produto algum a venda. <%= link_to t("new_prod"),
    	products_path %> agora mesmo. </p>
<% else %>
	<h3 class="text-center"> <%= t('products') %> </h3>
<% end %>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @products.each do |product| %>
      <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<h1>Novo Produto</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>